name: Checkout Example

on:
  push:
    branches: [ main ]

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Репозиторийді жүктеу (checkout)
        uses: actions/checkout@v3

      - name: Файлдардың тізімін шығару
        run: ls -la
